# Generated by Django 4.0.4 on 2022-05-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_month',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
