# Generated by Django 4.0.4 on 2022-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_purchase_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
